server:
  port: 7004
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zipkin?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ok123
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
zipkin:
  storage:
    type: mysql
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
