server:
  port: 9002
spring:
  application:
    name: QGGOODSERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qg_goods
    username: root
    password: ok123
  redis:
    database: 0
    host: localhost
    port: 6379
    password: ok
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
