server:
  port: 10010
spring:
  application:
    name: FORUM
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ant_community
    username: root
    password: ok
  redis:
    database: 0
    host: localhost
    port: 6379
  data:
    mongodb:
      database: articledb
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672
  elasticsearch:
    cluster-name: wf
    cluster-nodes: 127.0.0.1:9300
    repositories:
      enable: true
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml