
#  zipkin:
#    base-url: http://127.0.0.1:7004
#  sleuth:
#    sampler:
#      percentage: 1.0
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
server:
  port: 8001
spring:
  application:
    name: order-provider
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/