server:
  port: 7002
spring:
  application:
    name: my-cloud-hystrix-dashboard
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true
turbine:
  # 要监控的微服务列表，多个用,分隔
  app-config: user-consumer,user-consumer-feigin
  cluster-name-expression:  "'default'"
  instanceUrlSuffix:
    default: hystrix.stream
