server:
  port: 7003
spring:
  application:
    name: my-wf-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true #显示浏览器中的状态栏显示ip
zuul:
  routes:
    myuser-consumer:  # 这里是路由id，随意写
      path: /userserver/**   # 这里是映射路径
      serviceId: user-consumer-feigin #配置转发的微服务名称

  RouteFilter:
    pre:
      disable: true
  ratelimit:
    enabled: true #开启限流
    policies:
      myuser-consumer:
        limit: 10 #60s 内请求超过 3 次，服务端就抛出异常，60s 后可以恢复正常请求
        refresh-interval: 60
        type: origin #针对 IP 进行限流，不影响其他 IP
#  ratelimit:
#    enabled: true #开启限流
#    default-policy:
#      limit: 3 #60s 内请求超过 3 次，服务端就抛出异常，60s 后可以恢复正常请求
#      refresh-interval: 60
#      type: origin #针对 IP 进行限流，不影响其他 IP



