server:
  port: 8000
spring:
  application:
    name: USERSERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_user
    username: root
    password: ok
  redis:
    database: 0
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672
#    publisher-confirms: true
#    publisher-returns: true
#    template:
#      mandatory: true
#    listener:
#      simple:
#        acknowledge-mode: manual  #消费端手工ack的配置
#        concurrency: 1
#        max-concurrency: 5
  cache:
    ehcache:
      config: classpath:/ehcache.xml
    type: ehcache
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
