server:
  port: 7002
spring:
  application:
    name: GATEWAYSERVER
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true #显示浏览器中的状态栏显示ip
zuul:
  routes:
    mygoodserver:
      path: /goodserver/**        #http://localhost:7002/goodserver/user/show?uid=2
      serviceId: GOODSERVICE

  RouteFilter:
    pre:
      disable: true
  ratelimit:
    enabled: true #开启限流
    policies:
      mygoodserver:
        limit: 10 #60s 内请求超过 3 次，服务端就抛出异常，60s 后可以恢复正常请求
        refresh-interval: 10
        type: origin #针对 IP 进行限流，不影响其他 IP
