server:
  port: 9001
spring:
  application:
    name: consumer-feigin
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true #显示浏览器中的状态栏显示ip

feign:
  hystrix:
    enabled: true
