spring:
  application:
    name: AUTH2SERVER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qg_oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ok123
mybatis:
  mapper-locations: classpath:mapper/*.xml